#!/bin/bash

#%include helptext.sh

#%include std/autohelp.sh
#%include std/safe.sh
#%include std/varify.sh
#%include std/out.sh

#%include listing.sh

m3s:split() {
    local extents="$1"; shift

    TITLE="$1"; shift
    local title="$(varify:fil "$TITLE")"

    SUBFILE="$tracknum-$title"

    (set -x
        mp3cut -o "$SUBFILE.mp3" \
            -T "${TITLE:-}" \
            -A "${ARTIST:-}" \
            -N "${ALBUM:-}" \
            -t "$extents" \
            "$MAINMP3"
    )
}

m3s:set_variable() {
    case "$1" in
        %album)
            ALBUM="$2"
            ALBUMF="$(varify:fil "$ALBUM")"
            ;;
        %year)
            YEAR="$2" ;;
        %artist)
            ARTIST="$2"
            ARTISTF="$(varify:fil "$ARTIST")"
            ;;
        %genre)
            GENRE="$2" ;;
    esac
}

m3s:processtracks() {
    local token remains res
    res=0

    while read token trackn remains; do
        if [[ "$token" =~ ^% ]]; then
            m3s:set_variable "$token" "$trackn $remains"

        elif (echo "$token"|grep -Pq '^(\d\d:)?\d\d:\d\d-(\d\d:)?\d\d:\d\d$'); then
            tracknum="$trackn"
            [[ "${M3S_preprocess:-}" = true ]] || m3s:split "$token" "$remains"

        else
            out:error "Could not process line [$token] [$trackn] [$remains]"
            res=1
        fi
    done

    return $res
}

main() {
    autohelp:check "$@"
    [[ -n "$*" ]] || { autohelp:print ; exit 0 ; }

    TRACKFILE="${1:-}"; shift || out:fail "No track file specified"
    MAINMP3="${1:-}"; shift || out:fail "No MP3 file specified"

    ALBUM="$(varify:fil "${MAINMP3%.*}")"
    ALBUMF="$ALBUM"


    if [[ "$TRACKFILE" = length ]]; then
        m3s:listing:length "$MAINMP3"

    elif [[ "$MAINMP3" = align ]]; then
        m3s:listing:align

    else
        [[ -f "$MAINMP3" ]] || out:fail "'$MAINMP3' : not a file."

        # Process all lines first, without doing a conversion
        #   wrap in subshell to avoid inadvertently setting variables
        (m3s:listing:align | M3S_preprocess=true m3s:processtracks)

        m3s:listing:align | m3s:processtracks
    fi
}

main "$@"
