#!/bin/bash

### MP3 Splitter Usage:help
#
#      mp3split { align | MP3FILE } TRACKFILE
#
# Split an MP3 into several files, according to its track list.
#
# Use the `align` command instead of an MP3 file name to see how the track listing is processed.
#
# MP3FILE must be a path to an MP3 file.
#
# The track list must match the below format, specifying time extents, then track number, then the track title.
# Meta variables at the top of the file can be specified for the IDv3 tags.
# Blank lines and lines starting with `#` are ignored.
#
#
#      %artist Artist Name
#      %album Album Title
#
#      00:00:00-00:02:31 01 Title of first track
#      00:02:31-00:05:13 02 Second track's title
#
#
# If you only have a file with track start times like
#
#      00:00:00 01 Title of first track
#      00:02:31 02 Second track's title
#      00:05:13 (end of tracks)
# 
# Then you can run `mp3split align your-trackfile.txt` ; this will align all the times found in the file, though note that the last time entry should simply be the end of the last track.
#
#
# You can spread variables around the file too; this is typically useful for including additional artists
#
#      %artist Music Pearson
#      %album Album Title
#
#      00:00:00-00:02:31 01 First Track
#
#      %artist Music Pearson, feat. Guy Other
#      00:02:31-00:05:13 02 Collabo Title (feat. Guy Other)
#
#      %artist Music Pearson
#      00:05:13-00:07:42 03 Back to Soloing
# 
###/doc

# not supported - need to use an IDv3 tag editor after the fiels are split out
#
#   %year Year
#   %genre Genre description
#
# ##/doc

#%include autohelp.sh safe.sh varify.sh out.sh
#%include listing.sh

m3s:split() {
    local extents="$1"; shift

    TITLE="$1"; shift
    local title="$(varify:fil "$TITLE")"

    SUBFILE="$tracknum-$title"

    (set -x
        mp3cut -o "$SUBFILE.mp3" -T "${TITLE:-}" -A "${ARTIST:-}" -N "${ALBUM:-}" -t "$extents" "$MAINMP3"
    )
}

m3s:set_variable() {
    case "$1" in
        %album)
            ALBUM="$2"
            ALBUMF="$(varify:fil "$ALBUM")"
            ;;
        %year)
            YEAR="$2" ;;
        %artist)
            ARTIST="$2"
            ARTISTF="$(varify:fil "$ARTIST")"
            ;;
        %genre)
            GENRE="$2" ;;
    esac
}

m3s:readtracks() {
    local token remains res
    res=0

    while read token trackn remains; do
        if (echo "$token"|grep -Pq '(^\s*#)|(^\s*$)'); then
            continue

        elif [[ "$token" =~ ^% ]]; then
            m3s:set_variable "$token" "$trackn $remains"

        elif (echo "$token"|grep -Pq '^(\d\d:)?\d\d:\d\d-(\d\d:)?\d\d:\d\d$'); then
            tracknum="$trackn"
            [[ "${M3S_preprocess:-}" = true ]] || m3s:split "$token" "$remains"

        else
            out:error "Could not process line [$token] [$trackn] [$remains]"
            res=1
        fi
    done

    return $res
}


main() {
    autohelp:check "$@"
    [[ -n "$*" ]] || { autohelp:print ; exit 0 ; }

    MAINMP3="$1"; shift || :
    TRACKFILE="$1"; shift || :

    ALBUM="$(varify:fil "${MAINMP3%.*}")"
    ALBUMF="$ALBUM"


    if [[ "$MAINMP3" = align ]]; then
        m3s:listing:frontify < "$TRACKFILE" | m3s:listing:align_times
    else
        [[ -f "$MAINMP3" ]] || out:fail "'$MAINMP3' : not a file."

        # Process all lines first, without doing a conversion
        #   wrap in subshell to avoid inadvertently setting variables
        (m3s:listing:frontify < "$TRACKFILE" | m3s:listing:align_times | M3S_preprocess=true m3s:readtracks)

        m3s:listing:frontify < "$TRACKFILE" | m3s:listing:align_times | m3s:readtracks
    fi
}

main "$@"
